spring:
  application:
    name: api.fala
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      audio:
        transcription:
          options:
            model: whisper-1
            language: pt
            temperature: 0
            response-format: text
            prompt: >-
              Audio em portugues brasileiro, audio contem descrição de gastos financeiros.
              As frases geralmente contem:
              - um valor em reais (numero + reais);
              - um ação (gastei, paguei. comprei);
              - um local ou estabelecimento (mercado, farmacia, restaurante, loja, etc...)

logging:
  level:
    org.springframework.ai: DEBUG

